package render

import (
	"strings"

	"trustpanel/internal/core/model"
)

// renderCredentials emits the TrustTunnel credentials.toml for the given active
// users. Username/password MUST match the sing-box inbound users[] rendered
// from the same projection, so that the username TrustTunnel forwards over
// RFC1929 authenticates against sing-box and sets metadata.User for
// auth_user routing.
func renderCredentials(active []model.User) string {
	var b strings.Builder
	b.WriteString("# Generated by TrustPanel. Do not edit by hand.\n")
	b.WriteString("# TrustTunnel client credentials; keep this file private.\n\n")
	for _, u := range active {
		b.WriteString("[[client]]\n")
		b.WriteString("username = " + tomlString(u.Username) + "\n")
		b.WriteString("password = " + tomlString(u.Secret) + "\n\n")
	}
	return b.String()
}

// tomlString returns a TOML basic string with the minimal escaping TrustTunnel
// credentials need (backslash and double-quote).
func tomlString(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + r.Replace(s) + `"`
}
