package render

import (
	"fmt"
	"sort"
	"strings"

	"trustpanel/internal/core/model"
)

// renderTrustTunnel produces the TrustTunnel endpoint config for an entry node:
// vpn.toml, hosts.toml, rules.toml. credentials.toml is produced separately
// from the same user projection.
//
// The endpoint terminates users and forwards ALL traffic to the local sing-box
// mixed inbound over SOCKS5 with extended_auth=false: the verified path that
// carries the client's RFC1929 username to sing-box for auth_user routing.
func renderTrustTunnel(state model.State, node model.Node, opts Options) ([]Artifact, []string) {
	domain, warnings := entryDomain(state, node.ID)
	socksAddr := fmt.Sprintf("%s:%d", opts.MixedListen, opts.MixedPort)

	vpn := vpnToml(opts, socksAddr)
	hosts := hostsToml(state, node.ID, domain, opts)
	rules := rulesToml()

	return []Artifact{
		newArtifact(vpnPath, 0o600, vpn),
		newArtifact(hostsPath, 0o600, hosts),
		newArtifact(rulesPath, 0o644, rules),
	}, warnings
}

// entryDomain returns the main-fallback hostname for the node.
func entryDomain(state model.State, nodeID string) (string, []string) {
	var first string
	for _, d := range state.Domains {
		if d.NodeID != nodeID {
			continue
		}
		if d.Purpose == model.PurposeMainFallback {
			return d.Hostname, nil
		}
		if first == "" {
			first = d.Hostname
		}
	}
	if first != "" {
		return first, []string{fmt.Sprintf("entry %q has no main-fallback domain; using %q", nodeID, first)}
	}
	return "vpn.example.invalid", []string{fmt.Sprintf("entry %q has no domain assigned; emitted a placeholder hostname", nodeID)}
}

func vpnToml(opts Options, socksAddr string) string {
	return fmt.Sprintf(`# Generated by TrustPanel. Do not edit by hand.
# TrustTunnel endpoint config.

credentials_file = "credentials.toml"
rules_file = "rules.toml"
listen_address = %q
non_connect_auth_failure_status_code = 404

[listen_protocols.http1]
upload_buffer_size = 32768

[listen_protocols.http2]
initial_connection_window_size = 8388608
initial_stream_window_size = 131072
max_concurrent_streams = 1000
max_frame_size = 16384
header_table_size = 65536

# Forward all user traffic to the local sing-box policy router:
# extended_auth=false carries the client's RFC1929 username for auth_user.
[forward_protocol.socks5]
address = %q
extended_auth = false

# Same-domain browser fallback to the local camouflage origin.
[reverse_proxy]
server_address = %q
path_mask = "/"
`, opts.TrustTunnelListen, socksAddr, opts.FallbackOrigin)
}

func hostsToml(state model.State, nodeID, mainDomain string, opts Options) string {
	var b strings.Builder
	b.WriteString("# Generated by TrustPanel. Do not edit by hand.\n")
	b.WriteString("# TrustTunnel TLS host bindings.\n\n")
	b.WriteString("[[main_hosts]]\n")
	b.WriteString("hostname = " + tomlString(mainDomain) + "\n")
	b.WriteString("cert_chain_path = " + tomlString(opts.CertChainPath) + "\n")
	b.WriteString("private_key_path = " + tomlString(opts.PrivateKeyPath) + "\n\n")

	// Additional fallback-site hostnames on the node become reverse_proxy_hosts.
	var extra []string
	for _, d := range state.Domains {
		if d.NodeID == nodeID && d.Purpose == model.PurposeFallbackSite && d.Hostname != mainDomain {
			extra = append(extra, d.Hostname)
		}
	}
	sort.Strings(extra)
	for _, h := range extra {
		b.WriteString("[[reverse_proxy_hosts]]\n")
		b.WriteString("hostname = " + tomlString(h) + "\n")
		b.WriteString("cert_chain_path = " + tomlString(opts.CertChainPath) + "\n")
		b.WriteString("private_key_path = " + tomlString(opts.PrivateKeyPath) + "\n\n")
	}
	return b.String()
}

func rulesToml() string {
	return `# Generated by TrustPanel. Do not edit by hand.
# Per-user/domain routing lives in sing-box (auth_user rules), not here.
# TrustTunnel rules match cidr/client_random_prefix only; none are needed.
`
}
