package provision

import (
	"context"
	"fmt"
	"strconv"
	"strings"
)

// Hardening configures optional server hardening run as the last provisioning
// step. Disabling password auth is gated on a verified SSH key being installed,
// so a misconfiguration cannot lock the operator out.
type Hardening struct {
	Enabled             bool   `json:"enabled"`
	SudoUser            string `json:"sudo_user"`
	SSHPubKey           string `json:"ssh_pubkey"`
	SSHPort             int    `json:"ssh_port"`
	DisableRootLogin    bool   `json:"disable_root_login"`
	DisablePasswordAuth bool   `json:"disable_password_auth"`
	Fail2ban            bool   `json:"fail2ban"`
	Firewall            bool   `json:"firewall"`
	AgentPort           int    `json:"agent_port"` // mTLS control port to open (default 8443)
}

// Harden applies optional server hardening (sudo user + key, fail2ban, sshd
// drop-in, firewall) over the runner. It is the exported entry point used by
// bootstrap to harden a one-box install locally; the SSH provisioning path
// calls the same logic as its final step.
func Harden(ctx context.Context, r Runner, h *Hardening, step func(string)) error {
	if h == nil || !h.Enabled {
		return nil
	}
	return harden(ctx, r, h, step)
}

func harden(ctx context.Context, r Runner, h *Hardening, step func(string)) error {
	keyInstalled := false

	// 0. Refresh the package index once if we will install anything. A stock
	// server often has an empty apt cache, so `apt-get install` finds "no
	// installation candidate" — update first so fail2ban/ufw actually install.
	if h.Fail2ban || h.Firewall {
		_, _ = r.Run(ctx, "command -v apt-get >/dev/null && DEBIAN_FRONTEND=noninteractive apt-get update -qq || true")
	}

	// 1. Create the sudo user (passwordless sudo) and install its SSH key.
	if h.SudoUser != "" {
		u := h.SudoUser
		if !validUser(u) {
			return fmt.Errorf("invalid sudo user %q", u)
		}
		create := strings.Join([]string{
			"id -u " + u + " >/dev/null 2>&1 || useradd -m -s /bin/bash " + u,
			"usermod -aG sudo " + u + " 2>/dev/null || usermod -aG wheel " + u + " 2>/dev/null || true",
			"printf '%s ALL=(ALL) NOPASSWD:ALL\\n' " + u + " > /etc/sudoers.d/90-" + u,
			"chmod 440 /etc/sudoers.d/90-" + u,
		}, " && ")
		if _, err := r.Run(ctx, create); err != nil {
			return fmt.Errorf("create sudo user: %w", err)
		}
		step("hardening: sudo user " + u)

		if strings.TrimSpace(h.SSHPubKey) != "" {
			home := "/home/" + u
			if _, err := r.Run(ctx, "install -d -m 700 "+home+"/.ssh"); err != nil {
				return fmt.Errorf("ssh dir: %w", err)
			}
			if err := r.Put(ctx, []byte(strings.TrimSpace(h.SSHPubKey)+"\n"), home+"/.ssh/authorized_keys", 0o600); err != nil {
				return fmt.Errorf("authorized_keys: %w", err)
			}
			if _, err := r.Run(ctx, "chown -R "+u+":"+u+" "+home+"/.ssh"); err != nil {
				return fmt.Errorf("chown ssh: %w", err)
			}
			// Lock-out guard: confirm the key file is in place before we ever
			// disable password authentication.
			if out, err := r.Run(ctx, "test -s "+home+"/.ssh/authorized_keys && echo OK"); err == nil && strings.Contains(out, "OK") {
				keyInstalled = true
			}
			step("hardening: ssh key installed for " + u)
		}
	}

	// 2. fail2ban — installed BEFORE any SSH port / firewall change, while the
	// runner can still reconnect on the original port.
	if h.Fail2ban {
		install := "(command -v apt-get >/dev/null && DEBIAN_FRONTEND=noninteractive apt-get install -y fail2ban) || " +
			"(command -v dnf >/dev/null && dnf install -y fail2ban) || (command -v pacman >/dev/null && pacman -S --noconfirm fail2ban) || true"
		if _, err := r.Run(ctx, install+"; systemctl enable --now fail2ban 2>/dev/null || true"); err != nil {
			return fmt.Errorf("fail2ban: %w", err)
		}
		step("hardening: fail2ban")
	}

	// 3. sshd drop-in (written now, reloaded in the final step). Always-safe
	// options apply; PasswordAuthentication is only disabled when a key was
	// verified.
	var dropin []string
	if h.SSHPort != 0 {
		dropin = append(dropin, "Port "+strconv.Itoa(h.SSHPort))
	}
	if h.DisableRootLogin {
		dropin = append(dropin, "PermitRootLogin no")
	}
	if h.DisablePasswordAuth && keyInstalled {
		dropin = append(dropin, "PubkeyAuthentication yes", "PasswordAuthentication no")
	} else if h.DisablePasswordAuth {
		step("hardening: SKIPPED disabling password auth — no verified SSH key (avoiding lock-out)")
	}
	if len(dropin) > 0 {
		conf := "# Generated by TrustPanel.\n" + strings.Join(dropin, "\n") + "\n"
		if _, err := r.Run(ctx, "mkdir -p /etc/ssh/sshd_config.d"); err != nil {
			return fmt.Errorf("sshd_config.d: %w", err)
		}
		if err := r.Put(ctx, []byte(conf), "/etc/ssh/sshd_config.d/10-trustpanel.conf", 0o644); err != nil {
			return fmt.Errorf("sshd drop-in: %w", err)
		}
		step("hardening: sshd drop-in written")
	}

	// 4. FINAL step: enable the firewall and reload sshd in a SINGLE command on
	// the established connection. Both the SSH port change and `ufw enable` cut
	// off new connections on the old path, so nothing may reconnect afterwards —
	// the established session survives a reload and ufw (established traffic is
	// allowed), and there is no further step. Firewall opens: ssh (new port or
	// 22), 443 (TrustTunnel/Reality), 80 (ACME HTTP-01 + fallback), and 8443 (the
	// agent's mTLS control channel — the panel pushes desired-state there; the
	// agent only honors CA-signed controller certs).
	var final []string
	if h.Firewall {
		sshPort := 22
		if h.SSHPort != 0 {
			sshPort = h.SSHPort
		}
		agentPort := 8443
		if h.AgentPort != 0 {
			agentPort = h.AgentPort
		}
		install := "command -v ufw >/dev/null || (command -v apt-get >/dev/null && DEBIAN_FRONTEND=noninteractive apt-get install -y ufw) || " +
			"(command -v dnf >/dev/null && dnf install -y ufw) || (command -v pacman >/dev/null && pacman -S --noconfirm ufw) || true"
		ufw := fmt.Sprintf("ufw allow %d/tcp && ufw allow 443/tcp && ufw allow 80/tcp && ufw allow %d/tcp && ufw --force enable",
			sshPort, agentPort)
		final = append(final, install, "(command -v ufw >/dev/null && ("+ufw+") || true)")
	}
	if len(dropin) > 0 {
		final = append(final, "(systemctl reload sshd 2>/dev/null || systemctl reload ssh 2>/dev/null || true)")
	}
	if len(final) > 0 {
		if _, err := r.Run(ctx, strings.Join(final, "; ")); err != nil {
			return fmt.Errorf("firewall/sshd apply: %w", err)
		}
		step("hardening: firewall + sshd applied")
	}
	return nil
}

func validUser(s string) bool {
	if s == "" || len(s) > 32 {
		return false
	}
	for _, r := range s {
		if !(r == '_' || r == '-' || (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9')) {
			return false
		}
	}
	return true
}
